export const nozzleAssemblyHours = {
  500: {
    "Inner ring assembly": 4,
    "Inner ring assembly (st. st. ring or different plate thicknesses)": 7,
    "Base plate assembly and disassembly (in the nozzle)": 3,
    "Inlet profile assembly": 3,
    "Outlet profile assembly": 3,
    "Segments assembly (1 element between ribs and other transversal plates)": 1,
    "Rib assembly - 1 pc": 1.5,
    "Cone plates assembly - 1 row": 5,
    "Headbox plate assembly - 1 pc": 2,
    "Grindining": 7
  },
  600: {
    "Inner ring assembly": 4,
    "Inner ring assembly (st. st. ring or different plate thicknesses)": 8,
    "Base plate assembly and disassembly (in the nozzle)": 3,
    "Inlet profile assembly": 3,
    "Outlet profile assembly": 3,
    "Segments assembly (1 element between ribs and other transversal plates)": 1,
    "Rib assembly - 1 pc": 2,
    "Cone plates assembly - 1 row": 6,
    "Headbox plate assembly - 1 pc": 2,
    "Grindining": 8
  },
  700: {
    "Inner ring assembly": 4,
    "Inner ring assembly (st. st. ring or different plate thicknesses)": 9,
    "Base plate assembly and disassembly (in the nozzle)": 3.5,
    "Inlet profile assembly": 3.5,
    "Outlet profile assembly": 3.5,
    "Segments assembly (1 element between ribs and other transversal plates)": 1,
    "Rib assembly - 1 pc": 2,
    "Cone plates assembly - 1 row": 6,
    "Headbox plate assembly - 1 pc": 2,
    "Grindining": 8.5
  },
  800: {
    "Inner ring assembly": 4,
    "Inner ring assembly (st. st. ring or different plate thicknesses)": 9,
    "Base plate assembly and disassembly (in the nozzle)": 4,
    "Inlet profile assembly": 4,
    "Outlet profile assembly": 4,
    "Segments assembly (1 element between ribs and other transversal plates)": 1,
    "Rib assembly - 1 pc": 2,
    "Cone plates assembly - 1 row": 7,
    "Headbox plate assembly - 1 pc": 2,
    "Grindining": 9
  },
  900: {
    "Inner ring assembly": 4,
    "Inner ring assembly (st. st. ring or different plate thicknesses)": 10,
    "Base plate assembly and disassembly (in the nozzle)": 4,
    "Inlet profile assembly": 4,
    "Outlet profile assembly": 4,
    "Segments assembly (1 element between ribs and other transversal plates)": 1,
    "Rib assembly - 1 pc": 2,
    "Cone plates assembly - 1 row": 7,
    "Headbox plate assembly - 1 pc": 2,
    "Grindining": 9.5
  },
  1000: {
    "Inner ring assembly": 4,
    "Inner ring assembly (st. st. ring or different plate thicknesses)": 11.5,
    "Base plate assembly and disassembly (in the nozzle)": 5,
    "Inlet profile assembly": 5,
    "Outlet profile assembly": 5,
    "Segments assembly (1 element between ribs and other transversal plates)": 1,
    "Rib assembly - 1 pc": 2,
    "Cone plates assembly - 1 row": 8,
    "Headbox plate assembly - 1 pc": 2.5,
    "Grindining": 10
  },
  1200: {
    "Inner ring assembly": 4,
    "Inner ring assembly (st. st. ring or different plate thicknesses)": 12,
    "Base plate assembly and disassembly (in the nozzle)": 5,
    "Inlet profile assembly": 5.5,
    "Outlet profile assembly": 5.5,
    "Segments assembly (1 element between ribs and other transversal plates)": 1.5,
    "Rib assembly - 1 pc": 2,
    "Cone plates assembly - 1 row": 8,
    "Headbox plate assembly - 1 pc": 3,
    "Grindining": 10.5
  },
  1400: {
    "Inner ring assembly": 4,
    "Inner ring assembly (st. st. ring or different plate thicknesses)": 12.5,
    "Base plate assembly and disassembly (in the nozzle)": 5,
    "Inlet profile assembly": 5.5,
    "Outlet profile assembly": 5.5,
    "Segments assembly (1 element between ribs and other transversal plates)": 1.5,
    "Rib assembly - 1 pc": 2,
    "Cone plates assembly - 1 row": 9,
    "Headbox plate assembly - 1 pc": 3.5,
    "Grindining": 11
  },
  1600: {
    "Inner ring assembly": 5,
    "Inner ring assembly (st. st. ring or different plate thicknesses)": 13,
    "Base plate assembly and disassembly (in the nozzle)": 5,
    "Inlet profile assembly": 6.5,
    "Outlet profile assembly": 6.5,
    "Segments assembly (1 element between ribs and other transversal plates)": 1.5,
    "Rib assembly - 1 pc": 2,
    "Cone plates assembly - 1 row": 9,
    "Headbox plate assembly - 1 pc": 4,
    "Grindining": 12
  },
  1800: {
    "Inner ring assembly": 5,
    "Inner ring assembly (st. st. ring or different plate thicknesses)": 13.5,
    "Base plate assembly and disassembly (in the nozzle)": 5,
    "Inlet profile assembly": 7,
    "Outlet profile assembly": 7,
    "Segments assembly (1 element between ribs and other transversal plates)": 1.5,
    "Rib assembly - 1 pc": 2,
    "Cone plates assembly - 1 row": 10,
    "Headbox plate assembly - 1 pc": 4.5,
    "Grindining": 13
  },
  2000: {
    "Inner ring assembly": 6,
    "Inner ring assembly (st. st. ring or different plate thicknesses)": 14,
    "Base plate assembly and disassembly (in the nozzle)": 6,
    "Inlet profile assembly": 7.5,
    "Outlet profile assembly": 7.5,
    "Segments assembly (1 element between ribs and other transversal plates)": 1.5,
    "Rib assembly - 1 pc": 2.5,
    "Cone plates assembly - 1 row": 10,
    "Headbox plate assembly - 1 pc": 5,
    "Grindining": 14
  }
};
